"""empty message

Revision ID: 0d5fb9d2b963
Revises: b9cb503785c4
Create Date: 2018-12-10 15:28:17.896352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d5fb9d2b963'
down_revision = 'b9cb503785c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('front_user', sa.Column('last_login_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('front_user', 'last_login_time')
    # ### end Alembic commands ###
