"""empty message

Revision ID: 1e4ff237c3b7
Revises: 0d735628f9a5
Create Date: 2018-12-08 20:32:38.318290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e4ff237c3b7'
down_revision = '0d735628f9a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('read_nums', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'read_nums')
    # ### end Alembic commands ###
