"""empty message

Revision ID: 749c1009ae98
Revises: cdce76c964c6
Create Date: 2018-12-07 21:39:37.152706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '749c1009ae98'
down_revision = 'cdce76c964c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('author_id', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'post', 'front_user', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'author_id')
    # ### end Alembic commands ###
