"""empty message

Revision ID: 913b34190feb
Revises: 218e803500d8
Create Date: 2018-12-09 20:01:33.243863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '913b34190feb'
down_revision = '218e803500d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requestcount',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signin_counts', sa.Integer(), nullable=True),
    sa.Column('signup_counts', sa.Integer(), nullable=True),
    sa.Column('front_index_counts', sa.Integer(), nullable=True),
    sa.Column('post_counts', sa.Integer(), nullable=True),
    sa.Column('comment_counts', sa.Integer(), nullable=True),
    sa.Column('common_index_counts', sa.Integer(), nullable=True),
    sa.Column('captcha_counts', sa.Integer(), nullable=True),
    sa.Column('sms_captcha_counts', sa.Integer(), nullable=True),
    sa.Column('uptoken_counts', sa.Integer(), nullable=True),
    sa.Column('cms_index_counts', sa.Integer(), nullable=True),
    sa.Column('cms_logout_counts', sa.Integer(), nullable=True),
    sa.Column('cms_login_counts', sa.Integer(), nullable=True),
    sa.Column('cms_request_counts', sa.Integer(), nullable=True),
    sa.Column('front_request_counts', sa.Integer(), nullable=True),
    sa.Column('total_request_counts', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requestcount')
    # ### end Alembic commands ###
