"""empty message

Revision ID: b9cb503785c4
Revises: c40148187579
Create Date: 2018-12-09 20:53:35.155064

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b9cb503785c4'
down_revision = 'c40148187579'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requestcount', 'cms_request_counts')
    op.drop_column('requestcount', 'signin_counts')
    op.drop_column('requestcount', 'comment_counts')
    op.drop_column('requestcount', 'front_request_counts')
    op.drop_column('requestcount', 'cms_index_counts')
    op.drop_column('requestcount', 'common_index_counts')
    op.drop_column('requestcount', 'uptoken_counts')
    op.drop_column('requestcount', 'captcha_counts')
    op.drop_column('requestcount', 'signup_counts')
    op.drop_column('requestcount', 'sms_captcha_counts')
    op.drop_column('requestcount', 'total_request_counts')
    op.drop_column('requestcount', 'post_counts')
    op.drop_column('requestcount', 'cms_logout_counts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requestcount', sa.Column('cms_logout_counts', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('requestcount', sa.Column('post_counts', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('requestcount', sa.Column('total_request_counts', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('requestcount', sa.Column('sms_captcha_counts', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('requestcount', sa.Column('signup_counts', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('requestcount', sa.Column('captcha_counts', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('requestcount', sa.Column('uptoken_counts', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('requestcount', sa.Column('common_index_counts', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('requestcount', sa.Column('cms_index_counts', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('requestcount', sa.Column('front_request_counts', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('requestcount', sa.Column('comment_counts', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('requestcount', sa.Column('signin_counts', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('requestcount', sa.Column('cms_request_counts', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
