"""empty message

Revision ID: c40148187579
Revises: 913b34190feb
Create Date: 2018-12-09 20:47:43.617002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c40148187579'
down_revision = '913b34190feb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requestcount', sa.Column('create_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requestcount', 'create_time')
    # ### end Alembic commands ###
